### ISSUE TITLE
Mojo::DOM in Mojolicious >= 5.71 returns undef

### ISSUE THREAD

**Issue by reneeb** [Akron/Mojolicious-Plugin-XML-Loy#1]
https://github.com/Akron/Mojolicious-Plugin-XML-Loy/blob/master/t/XML-Loy.t#L141 checks for the empty string, but Mojo::DOM in Mojolicious >= 5.71 returns undef. See https://github.com/kraih/mojo/commit/5420cdbcdd8865d630f3ca33a3ae9d2729f5b54d

**Comment by reneeb** [comment]
A simple fix is to use "//" in https://github.com/Akron/XML-Loy/blob/master/lib/XML/Loy.pm#L566:

```
 return $self->SUPER::namespace // '' unless $_[0];
```

Other return values of Mojo::DOM should be checked, too.

**Comment by Akron** [comment]
Thank you! Yes - I can conform that this is mainly a problem with XML::Loy. I will have to add some more tests there to cover the API changes in Mojo::DOM. I hope I will find the time tomorrow!

**Comment by Akron** [comment]
This should be fixed now in XML::Loy 0.33 and M::P::XML::Loy 0.11. Thank you again!
